// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entity;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    [Column(TypeName ="decimal(18,2)")]

    public decimal Price { get; set; }

    public int CategoryId { get; set; }

    public string Description { get; set; }

    public virtual Category Category { get; set; }

    public virtual OrderItem OrderItem { get; set; }
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}